import type { FlowConfig } from "@/lib/flow-types";

export const caTrvF1Flow: FlowConfig = {
  id: "ca-trv-f1-adult",
  version: "0.1",
  countryCode: "CA",
  countrySlug: "ca",
  countryName: "加拿大",
  visaType: "访客签证（TRV）",
  visaTypeSlug: "visitor",
  status: "F1",
  statusSlug: "f1",
  statusLabel: "F-1 在读学生",
  audience: "持中国护照、年满 18 岁、目前以 F-1 身份在美国学习的申请人",
  lastVerified: "2026-06-23",
  officialFee: "CAD 100（提交时以 IRCC 页面为准）",
  biometricsFee: "通常为 CAD 85（如需采集，以 IRCC 页面为准）",
  eligibilityChoices: [
    {
      id: "F1",
      label: "F-1 在读学生",
      supported: true,
      note: "0.1 版本支持",
    },
    {
      id: "OPT",
      label: "OPT / STEM OPT",
      supported: false,
      note: "后续版本",
    },
    {
      id: "H",
      label: "H 类身份",
      supported: false,
      note: "后续版本",
    },
    {
      id: "J",
      label: "J 类身份",
      supported: false,
      note: "后续版本",
    },
    {
      id: "M",
      label: "M 类身份",
      supported: false,
      note: "后续版本",
    },
    {
      id: "L",
      label: "L 类身份",
      supported: false,
      note: "后续版本",
    },
  ],
  sources: [
    {
      id: "visitor-overview",
      label: "加拿大访客签证说明",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/about-visitor-visa.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "eligibility",
      label: "访客签证申请资格",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eligibility.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "apply",
      label: "访客签证申请步骤与官方入口",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "account",
      label: "IRCC 账户入口说明",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "biometrics",
      label: "生物信息采集要求与地点",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/biometrics/where-to-give.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "after-apply",
      label: "提交申请后的官方流程",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/after-apply-next-steps.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "processing-times",
      label: "官方处理时间查询",
      organization: "加拿大移民、难民及公民部（IRCC）",
      url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html",
      lastVerified: "2026-06-23",
    },
    {
      id: "vfs-us",
      label: "美国加拿大签证申请中心",
      organization: "VFS Global",
      url: "https://visa.vfsglobal.com/usa/en/can/",
      lastVerified: "2026-06-23",
    },
  ],
  steps: [
    {
      id: "identity",
      slug: "identity",
      title: "确认身份与适用范围",
      summary: "先确认这条 F-1 流程是否适合你，再开始准备材料。",
      officialLinkIds: ["visitor-overview"],
      tasks: [
        { id: "chinese-passport", title: "我持中国普通护照", kind: "required" },
        { id: "in-us", title: "我目前人在美国", kind: "required" },
        { id: "f1-active", title: "我目前是 F-1 在读学生，不是 OPT", kind: "required" },
        { id: "adult", title: "我已年满 18 岁", kind: "required" },
        {
          id: "new-application",
          title: "我准备提交一份新的加拿大访客签证申请",
          kind: "required",
        },
      ],
    },
    {
      id: "eligibility",
      slug: "eligibility",
      title: "检查基本申请条件",
      summary: "发现明显不适合标准流程的情况；本站不代替 IRCC 作资格判断。",
      officialLinkIds: ["eligibility"],
      tasks: [
        { id: "valid-passport", title: "护照有效，并计划使用同一本护照申请和旅行", kind: "required" },
        { id: "short-visit", title: "访问目的为短期旅游或普通访问", kind: "required" },
        { id: "leave-canada", title: "我计划在访问结束后离开加拿大", kind: "required" },
        { id: "study-ties", title: "我能说明在美国的学习安排和返回约束", kind: "recommended" },
        { id: "enough-funds", title: "我能够承担申请和旅行费用", kind: "required" },
        {
          id: "complex-case",
          title: "我没有需要专业协助的复杂犯罪、移民或健康情况",
          kind: "conditional",
        },
      ],
    },
    {
      id: "overview",
      slug: "overview",
      title: "了解完整流程",
      summary: "先看清申请、指纹、审理和贴签全周期，避免只规划 IRCC 审理时间。",
      officialLinkIds: ["apply", "processing-times"],
      tasks: [
        { id: "understand-online", title: "我知道本流程需要在线申请", kind: "informational" },
        { id: "understand-fees", title: "我已了解申请费和可能的生物信息费", kind: "informational" },
        { id: "understand-timing", title: "我已为预约、审理和护照往返预留时间", kind: "recommended" },
        { id: "understand-no-guarantee", title: "我理解处理时间不是批准保证或最长时限", kind: "required" },
      ],
    },
    {
      id: "information",
      slug: "information",
      title: "准备个人与旅行信息",
      summary: "提前整理官方表格会询问的信息；本站不会保存具体答案。",
      officialLinkIds: ["apply"],
      tasks: [
        { id: "passport-info", title: "当前及旧护照信息", kind: "required" },
        { id: "us-address", title: "美国住址和联系方式", kind: "required" },
        { id: "school-info", title: "学校及当前学习信息", kind: "required" },
        { id: "travel-plan", title: "预计旅行日期、目的和简短行程", kind: "required" },
        { id: "history-info", title: "教育、工作和旅行经历", kind: "required" },
        { id: "family-info", title: "配偶、子女和父母等家庭信息", kind: "required" },
        { id: "application-history", title: "既往加拿大申请、入境和拒签记录", kind: "conditional" },
      ],
    },
    {
      id: "documents",
      slug: "documents",
      title: "准备申请材料",
      summary: "最终以 IRCC Portal 生成的个性化文件清单为准。",
      officialLinkIds: ["apply"],
      tasks: [
        { id: "passport-copy", title: "护照资料页及有签证、印章或标记的页面", kind: "required" },
        { id: "i20", title: "有效 I-20", kind: "required" },
        { id: "i94", title: "I-94 入境记录", kind: "recommended" },
        { id: "enrollment-letter", title: "学校在读证明", kind: "recommended" },
        { id: "itinerary", title: "旅行目的和行程说明", kind: "recommended" },
        { id: "financial-proof", title: "资金证明", kind: "recommended" },
        { id: "photo", title: "符合个性化清单要求的电子照片", kind: "conditional" },
        { id: "extra-documents", title: "Portal 要求的其他表格或补充材料", kind: "conditional" },
      ],
    },
    {
      id: "account",
      slug: "account",
      title: "进入 IRCC 官方系统",
      summary: "从加拿大政府页面选择当前适用的 Portal 或账户入口。",
      officialLinkIds: ["apply", "account"],
      tasks: [
        { id: "official-entry", title: "我从加拿大政府官方页面进入申请系统", kind: "required" },
        { id: "visitor-visa", title: "我确认选择的是 visitor visa", kind: "required" },
        { id: "account-created", title: "我已创建账户或成功登录", kind: "required" },
        { id: "recovery-saved", title: "我已安全保存登录和恢复方式", kind: "recommended" },
        { id: "personal-checklist", title: "我已查看系统生成的个性化材料清单", kind: "required" },
      ],
    },
    {
      id: "application",
      slug: "application",
      title: "填写在线申请",
      summary: "按官方系统逐项如实填写；本站不复制问题、不代填答案。",
      officialLinkIds: ["apply"],
      tasks: [
        { id: "travel-section", title: "旅行计划", kind: "required" },
        { id: "personal-section", title: "个人、护照和美国身份信息", kind: "required" },
        { id: "activity-section", title: "教育、工作和旅行历史", kind: "required" },
        { id: "financial-section", title: "财务信息", kind: "required" },
        { id: "family-section", title: "家庭信息", kind: "required" },
        { id: "background-section", title: "安全、医疗和移民背景问题", kind: "required" },
        { id: "contact-section", title: "联系方式", kind: "required" },
      ],
    },
    {
      id: "submission",
      slug: "submission",
      title: "上传、核对、缴费并提交",
      summary: "提交前完成最后核对，并保存确认页和收据。",
      officialLinkIds: ["apply"],
      timelineEvent: {
        id: "applicationSubmittedAt",
        label: "在线提交日期",
        description: "只记录日期，用于计算你自己的流程耗时。",
      },
      tasks: [
        { id: "all-files-uploaded", title: "已上传个性化清单要求的全部文件", kind: "required" },
        { id: "files-readable", title: "文件清晰、方向正确且可以打开", kind: "required" },
        { id: "details-match", title: "表单与护照、I-20 等文件一致", kind: "required" },
        { id: "declaration-read", title: "已阅读声明并完成官方电子签署", kind: "required" },
        { id: "fees-paid", title: "已按官方页面显示金额缴费", kind: "required" },
        { id: "confirmation-saved", title: "已保存提交确认和缴费收据", kind: "recommended" },
      ],
    },
    {
      id: "biometrics-letter",
      slug: "biometrics-letter",
      title: "等待生物信息采集通知",
      summary: "查看 IRCC 账户和邮箱，确认是否需要采集生物信息。",
      officialLinkIds: ["biometrics", "after-apply"],
      timelineEvent: {
        id: "biometricsLetterReceivedAt",
        label: "收到 BIL 日期",
        description: "如无需采集，可以留空。",
      },
      tasks: [
        { id: "check-account", title: "定期查看 IRCC 账户", kind: "required" },
        { id: "check-email", title: "查看邮箱和垃圾邮件", kind: "recommended" },
        { id: "bil-status", title: "已确认是否收到 Biometrics Instruction Letter", kind: "required" },
        { id: "biometrics-validity", title: "已通过官方工具核对既往生物信息有效性", kind: "conditional" },
      ],
    },
    {
      id: "biometrics",
      slug: "biometrics",
      title: "完成生物信息采集",
      summary: "收到 BIL 后按信件期限尽快预约；最终要求以你的 BIL 为准。",
      officialLinkIds: ["biometrics"],
      timelineEvent: {
        id: "biometricsCompletedAt",
        label: "完成生物信息采集日期",
        description: "如官方确认无需采集，可以留空。",
      },
      tasks: [
        { id: "bil-deadline", title: "已阅读 BIL 中的地点和截止日期", kind: "required" },
        { id: "appointment-booked", title: "已通过官方入口预约采集点", kind: "required" },
        { id: "appointment-saved", title: "已保存预约确认", kind: "recommended" },
        { id: "biometrics-docs", title: "已准备护照、BIL 和预约要求文件", kind: "required" },
        { id: "biometrics-done", title: "已完成指纹和照片采集", kind: "required" },
      ],
    },
    {
      id: "processing",
      slug: "processing",
      title: "等待审理并处理额外要求",
      summary: "继续查看账户；如收到补件、面试或体检要求，以官方通知为准。",
      officialLinkIds: ["after-apply", "processing-times"],
      tasks: [
        { id: "monitor-status", title: "定期查看 IRCC 账户和邮箱", kind: "required" },
        { id: "additional-request", title: "如收到额外要求，已按通知处理", kind: "conditional" },
        { id: "timing-expectation", title: "没有把预计处理时间理解为批准保证", kind: "required" },
      ],
    },
    {
      id: "passport-request",
      slug: "passport-request",
      title: "收到护照递交通知",
      summary: "收到 IRCC 正式通知后再准备递交护照。",
      officialLinkIds: ["after-apply"],
      timelineEvent: {
        id: "passportRequestReceivedAt",
        label: "收到护照递交通知日期",
        description: "以 IRCC 账户内正式通知日期为准。",
      },
      tasks: [
        { id: "official-ppr", title: "已在 IRCC 账户收到正式护照递交通知", kind: "required" },
        { id: "ppr-deadline", title: "已确认通知中的截止日期", kind: "required" },
        { id: "same-passport", title: "已确认递交申请时使用的同一本护照", kind: "required" },
        { id: "vfs-requirements", title: "已阅读 VFS 美国站最新递交要求", kind: "required" },
      ],
    },
    {
      id: "passport-submission",
      slug: "passport-submission",
      title: "向签证申请中心递交护照",
      summary: "地址、费用和寄送方式变化较快，只按 VFS 官方当前说明操作。",
      officialLinkIds: ["vfs-us"],
      timelineEvent: {
        id: "passportSubmittedAt",
        label: "寄出或递交护照日期",
        description: "用于估算贴签与返还阶段耗时。",
      },
      tasks: [
        { id: "original-passport", title: "护照原件", kind: "required" },
        { id: "ppr-letter", title: "IRCC 护照递交通知", kind: "required" },
        { id: "vfs-consent", title: "VFS 当前要求的同意书", kind: "required" },
        { id: "vfs-fees", title: "当前适用的服务费及付款方式", kind: "conditional" },
        { id: "delivery-method", title: "已确认寄送或现场递交方式", kind: "required" },
        { id: "return-shipping", title: "已安排护照返还", kind: "required" },
        { id: "tracking-saved", title: "已保存追踪号、收据和材料副本", kind: "recommended" },
      ],
    },
    {
      id: "passport-return",
      slug: "passport-return",
      title: "跟踪护照处理与返还",
      summary: "使用 VFS、IRCC 和承运商提供的方式跟踪，不向本站填写申请号。",
      officialLinkIds: ["vfs-us", "after-apply"],
      timelineEvent: {
        id: "passportReturnShippedAt",
        label: "护照开始返还日期",
        description: "如能从追踪信息确认，可记录该日期。",
      },
      tasks: [
        { id: "vac-received", title: "已确认签证申请中心收到护照", kind: "required" },
        { id: "tracking-monitored", title: "已查看 VFS 或快递追踪信息", kind: "recommended" },
        { id: "return-started", title: "已确认护照开始返还", kind: "required" },
      ],
    },
    {
      id: "complete",
      slug: "complete",
      title: "收到护照并核对签证",
      summary: "核对签证信息，完成本站申请流程。",
      officialLinkIds: ["visitor-overview"],
      timelineEvent: {
        id: "passportReceivedAt",
        label: "收到护照日期",
        description: "该日期用于计算从提交申请到收到护照的总耗时。",
      },
      tasks: [
        { id: "passport-received", title: "已收到护照且没有运输损坏", kind: "required" },
        { id: "name-checked", title: "签证姓名与护照一致", kind: "required" },
        { id: "passport-number-checked", title: "护照号码正确", kind: "required" },
        { id: "visa-details-checked", title: "签证类别、入境次数和有效期已核对", kind: "required" },
        { id: "records-saved", title: "已保存申请收据和决定记录", kind: "recommended" },
        { id: "entry-understood", title: "我理解签证不保证入境", kind: "required" },
      ],
    },
    {
      id: "timeline",
      slug: "timeline",
      title: "整理匿名时间线",
      summary: "检查本地记录；0.1 暂不上传数据，未来可选择匿名贡献聚合统计。",
      officialLinkIds: ["processing-times"],
      tasks: [
        { id: "timeline-reviewed", title: "我已检查各阶段日期是否准确", kind: "recommended" },
        { id: "privacy-understood", title: "我知道本站不会要求姓名、UCI 或申请号", kind: "informational" },
        { id: "official-vs-community", title: "我理解用户样本统计不等于官方处理时间", kind: "required" },
      ],
    },
  ],
};
